@startuml

Customer *- Address
Address *- Country
Country *- Area

class Customer {
    String name
    Address address

    boolean isCustomerInEurope()
}

class Address {
    Country country

    boolean isInEurope()
}

class Country {
    Area area
}

class Area {
    boolean isEurope()
}

@enduml