@startuml

package "Model" {
    interface Movie {
    }

    class RegularMovie {
    }

    class ChildrensMovie {
    }

    class NewReleaseMovie {
    }
}

package "GUI" {
    interface MoviePrinter {
    }

    class RegularMoviePrinter {
    }

    class ChildrensMoviePrinter {
    }

    class NewReleaseMoviePrinter {
    }
}

Movie <|-- RegularMovie
Movie <|-- ChildrensMovie
Movie <|-- NewReleaseMovie

MoviePrinter <|-- RegularMoviePrinter
MoviePrinter <|-- ChildrensMoviePrinter
MoviePrinter <|-- NewReleaseMoviePrinter

Movie .. MoviePrinter: can-print
RegularMovie .. RegularMoviePrinter : can-print
ChildrensMovie .. ChildrensMoviePrinter : can-print
NewReleaseMovie .. NewReleaseMoviePrinter : can-print


@enduml