@startuml

Movie "1" *-- "*" Rental
Rental "*" *-- "1" Customer

class Movie {
    int priceCode
}

class Rental {
    int daysRented
    double getCharge()
}

class Customer {
    String statement()
}

@enduml