@startuml

Movie "1" *-- "*" Rental
Rental "*" *-- "1" Customer

class Movie {
    int priceCode
}

class Rental {
    int daysRented
}

class Customer {
    private double amountFor(Rental)
    String statement()
}

@enduml